//
//	This file was generated by the GEOS Resource Compiler
//
//	DO NOT EDIT! Any changes will be lost!
//
//	Edit proper resource file instead.
//

void EnterDeskTop (void);

const void subMenu1 = {
	(char)12, (char)26,
	(int)0, (int)22,
	(char)(1 | VERTICAL),
	"quit", (char)MENU_ACTION, (int)EnterDeskTop,
};

void set40col (void);
void set80col (void);

const void subMenu2 = {
	(char)16, (char)44,
	(int)25, (int)60,
	(char)(2 | VERTICAL),
	"40 col", (char)MENU_ACTION, (int)set40col,
	"80 col", (char)MENU_ACTION, (int)set80col,
};


const void mainMenu = {
	(char)0, (char)15,
	(int)0, (int)58,
	(char)(2 | HORIZONTAL),
	"geos", (char)SUB_MENU, (int)&subMenu1,
	"width", (char)SUB_MENU, (int)&subMenu2,
};

